### ISSUE TITLE
ProductCollection doesn't read parent category

### ISSUE THREAD

**Issue by alvaro-canepa** [lovata/oc-shopaholic-plugin#35]
If we make
```php
$obList = ProductCollection::make()->category(2);
```
Only get products with direct category relation. Can't get child categories products.
Example: have this categories:
```yaml
ID1: 
  name: "Category Root"
  childs:
    ID2:
      name: "Child Category #1"
    ID3:
      name: "Child Category #3"
      childs:
        ID4:
          name: "Child Category #1 of Category #3"
```
How can I get nested products of category ID3?
`ProductCollection` must return products of ID3 and ID4 categories.

Thanks
